import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.getAll.useQuery(undefined, {
    refetchOnWindowFocus: false,
  });

  const returnBuffer = api.example.returnBuffer.useMutation();

  async function handleAppend() {
    const res = await returnBuffer.mutateAsync("test");
    console.log(res);
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <button
          className="rounded-md bg-white px-4 py-2"
          onClick={() => {
            void handleAppend();
          }}
        >
          Append
        </button>
      </main>
    </>
  );
}
